version: "3.7"

services:
   database_ignite:
      image: postgres
      container_name: postgres-database-container
      restart: always
      ports:
         - 5432:5432
      environment: 
         - POSTGRES_USER=docker_user
         - POSTGRES_PASSWORD=ignitepassword
         - POSTGRES_DB=rentx-database
      volumes: 
         - pgdata:/data/postgres

   app:
      build: .
      container_name: app-container
      ports: 
         - 3333:3333
      volumes: 
         - .:/usr/app
      links:
         - database_ignite
      depends_on: 
         - database_ignite

volumes: 
   pgdata:
      driver: local